In [1]:
import nltk
import tensorflow as tf 
import numpy as np

nltk.download("punkt")

sentence = "He is the king. The king is royal. She is the royal queen."
sentence = sentence.lower()
print(sentence)
to = nltk.word_tokenize(sentence)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
he is the king. the king is royal. she is the royal queen.


In [2]:
ts = set(to)
tm = list(ts)
t = []
for i in range(0, len(tm)):
    if tm[i] != ".":
        t.append(tm[i])
sent = sentence.split('.')

markers= []
for js in sent:
        markers.append(js.split())
markers.remove([])
print(markers)
data= []
for sent in markers:
    for word_index, word in enumerate(sent):
        for n_word in sent[max(word_index-2,0):min(word_index+2,len(sent))+1]:
            if n_word != word:
                data.append([word, n_word])
                
w2i = {}
i2w = {}
print(data)
for i in range(0, len(t)):
    w2i[t[i]] = i
    i2w[i] = t[i]

vocab_size = len(t)

def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp

x_train = []
y_train = []

for d in data:
    x_train.append(to_one_hot(w2i[d[0]], vocab_size))
    y_train.append(to_one_hot(w2i[d[1]], vocab_size))
    
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)

[['he', 'is', 'the', 'king'], ['the', 'king', 'is', 'royal'], ['she', 'is', 'the', 'royal', 'queen']]
[['he', 'is'], ['he', 'the'], ['is', 'he'], ['is', 'the'], ['is', 'king'], ['the', 'he'], ['the', 'is'], ['the', 'king'], ['king', 'is'], ['king', 'the'], ['the', 'king'], ['the', 'is'], ['king', 'the'], ['king', 'is'], ['king', 'royal'], ['is', 'the'], ['is', 'king'], ['is', 'royal'], ['royal', 'king'], ['royal', 'is'], ['she', 'is'], ['she', 'the'], ['is', 'she'], ['is', 'the'], ['is', 'royal'], ['the', 'she'], ['the', 'is'], ['the', 'royal'], ['the', 'queen'], ['royal', 'is'], ['royal', 'the'], ['royal', 'queen'], ['queen', 'the'], ['queen', 'royal']]


In [3]:
print(x_train)

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [4]:
print(x_train.shape, y_train.shape)

(34, 7) (34, 7)


In [5]:
x = tf.placeholder(tf.float32, shape=(None, vocab_size))
y_label = tf.placeholder(tf.float32, shape=(None, vocab_size))
print(x, y_label)

Tensor("Placeholder:0", shape=(?, 7), dtype=float32) Tensor("Placeholder_1:0", shape=(?, 7), dtype=float32)


In [6]:
EMBEDDING_DIM = 7

W1 = tf.Variable(tf.random_normal([vocab_size, EMBEDDING_DIM]))
print(W1)

<tf.Variable 'Variable:0' shape=(7, 7) dtype=float32_ref>


In [7]:
# Bias
b1 = tf.Variable(tf.random_normal([EMBEDDING_DIM]))
print(b1)

<tf.Variable 'Variable_1:0' shape=(7,) dtype=float32_ref>


In [8]:
hidden_representation = tf.add(tf.matmul(x, W1), b1)
print(hidden_representation)

Tensor("Add:0", shape=(?, 7), dtype=float32)


In [9]:
W2 = tf.Variable(tf.random_normal([EMBEDDING_DIM, vocab_size]))
print(W2)

<tf.Variable 'Variable_2:0' shape=(7, 7) dtype=float32_ref>


In [10]:
b2 = tf.Variable(tf.random_normal([vocab_size]))
print(W2)

<tf.Variable 'Variable_2:0' shape=(7, 7) dtype=float32_ref>


In [11]:
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_representation, W2), b2))
print(prediction)

Tensor("Softmax:0", shape=(?, 7), dtype=float32)


In [20]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init) 

# loss fn
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(y_label * tf.log(prediction), reduction_indices=[1]))

train_step = tf.train.GradientDescentOptimizer(0.9).minimize(cross_entropy_loss)
epoch = 10000

# train
for _ in range(epoch):
    sess.run(train_step, feed_dict={x: x_train, y_label: y_train})
    print('loss is : ', sess.run(cross_entropy_loss, feed_dict={x: x_train, y_label: y_train}))

loss is :  2.3506505
loss is :  2.0196762
loss is :  1.861751
loss is :  1.7670454
loss is :  1.7123395
loss is :  1.6747503
loss is :  1.6629467
loss is :  1.6361616
loss is :  1.6418661
loss is :  1.6063733
loss is :  1.6111537
loss is :  1.5769792
loss is :  1.5786595
loss is :  1.5520257
loss is :  1.5519037
loss is :  1.5314246
loss is :  1.5299506
loss is :  1.5138295
loss is :  1.5113285
loss is :  1.4982834
loss is :  1.4950393
loss is :  1.4842173
loss is :  1.4804739
loss is :  1.4713068
loss is :  1.4672657
loss is :  1.459367
loss is :  1.4551886
loss is :  1.4482896
loss is :  1.4440962
loss is :  1.4380032
loss is :  1.4338834
loss is :  1.4284533
loss is :  1.424468
loss is :  1.4195915
loss is :  1.4157808
loss is :  1.4113744
loss is :  1.4077623
loss is :  1.403762
loss is :  1.4003627
loss is :  1.3967198
loss is :  1.3935417
loss is :  1.3902196
loss is :  1.3872659
loss is :  1.384237
loss is :  1.3815095
loss is :  1.378753
loss is :  1.3762497
loss is :  1.373748

loss is :  1.3290752
loss is :  1.3282815
loss is :  1.3288733
loss is :  1.3281181
loss is :  1.3286864
loss is :  1.3279667
loss is :  1.3285147
loss is :  1.3278272
loss is :  1.3283572
loss is :  1.3276994
loss is :  1.328214
loss is :  1.3275831
loss is :  1.3280842
loss is :  1.3274778
loss is :  1.3279676
loss is :  1.3273833
loss is :  1.3278633
loss is :  1.327299
loss is :  1.3277707
loss is :  1.3272246
loss is :  1.3276893
loss is :  1.3271596
loss is :  1.3276186
loss is :  1.3271037
loss is :  1.3275578
loss is :  1.3270565
loss is :  1.3275064
loss is :  1.3270178
loss is :  1.3274637
loss is :  1.3269863
loss is :  1.3274294
loss is :  1.3269624
loss is :  1.3274028
loss is :  1.3269453
loss is :  1.3273834
loss is :  1.3269354
loss is :  1.3273705
loss is :  1.3269317
loss is :  1.3273642
loss is :  1.3269343
loss is :  1.327364
loss is :  1.3269435
loss is :  1.3273696
loss is :  1.326959
loss is :  1.3273813
loss is :  1.3269814
loss is :  1.327399
loss is :  1.32701

loss is :  1.3279201
loss is :  1.3284793
loss is :  1.328095
loss is :  1.3286085
loss is :  1.3282156
loss is :  1.3286759
loss is :  1.3282794
loss is :  1.3286809
loss is :  1.3282864
loss is :  1.3286268
loss is :  1.3282402
loss is :  1.3285193
loss is :  1.3281451
loss is :  1.3283658
loss is :  1.3280087
loss is :  1.3281744
loss is :  1.327838
loss is :  1.3279543
loss is :  1.3276411
loss is :  1.3277131
loss is :  1.3274252
loss is :  1.3274595
loss is :  1.3271976
loss is :  1.3271995
loss is :  1.3269639
loss is :  1.3269389
loss is :  1.3267297
loss is :  1.3266826
loss is :  1.3264987
loss is :  1.3264341
loss is :  1.3262748
loss is :  1.3261962
loss is :  1.3260605
loss is :  1.3259708
loss is :  1.3258575
loss is :  1.3257595
loss is :  1.3256674
loss is :  1.3255632
loss is :  1.3254913
loss is :  1.3253825
loss is :  1.3253292
loss is :  1.3252175
loss is :  1.325182
loss is :  1.3250681
loss is :  1.3250496
loss is :  1.3249345
loss is :  1.3249323
loss is :  1.324

loss is :  1.3289483
loss is :  1.3288866
loss is :  1.3291899
loss is :  1.329121
loss is :  1.3293804
loss is :  1.3292998
loss is :  1.3295099
loss is :  1.3294141
loss is :  1.3295707
loss is :  1.3294575
loss is :  1.3295593
loss is :  1.3294278
loss is :  1.3294765
loss is :  1.3293271
loss is :  1.329326
loss is :  1.3291606
loss is :  1.3291153
loss is :  1.3289372
loss is :  1.3288546
loss is :  1.3286675
loss is :  1.3285545
loss is :  1.3283627
loss is :  1.328227
loss is :  1.3280345
loss is :  1.327883
loss is :  1.3276937
loss is :  1.3275328
loss is :  1.3273499
loss is :  1.327185
loss is :  1.327012
loss is :  1.3268473
loss is :  1.326686
loss is :  1.3265258
loss is :  1.3263783
loss is :  1.326225
loss is :  1.326093
loss is :  1.3259488
loss is :  1.3258332
loss is :  1.3256998
loss is :  1.3256017
loss is :  1.32548
loss is :  1.3254004
loss is :  1.325291
loss is :  1.3252306
loss is :  1.3251339
loss is :  1.325094
loss is :  1.3250098
loss is :  1.3249913
loss 

loss is :  1.324404
loss is :  1.3246158
loss is :  1.324239
loss is :  1.3244565
loss is :  1.3240969
loss is :  1.3243201
loss is :  1.3239795
loss is :  1.3242084
loss is :  1.3238885
loss is :  1.3241237
loss is :  1.323826
loss is :  1.3240678
loss is :  1.3237941
loss is :  1.3240438
loss is :  1.3237957
loss is :  1.3240538
loss is :  1.3238342
loss is :  1.3241016
loss is :  1.3239126
loss is :  1.324191
loss is :  1.324036
loss is :  1.3243257
loss is :  1.324208
loss is :  1.3245103
loss is :  1.324433
loss is :  1.324749
loss is :  1.3247151
loss is :  1.325045
loss is :  1.3250569
loss is :  1.3254005
loss is :  1.3254589
loss is :  1.3258156
loss is :  1.325919
loss is :  1.3262869
loss is :  1.3264307
loss is :  1.3268069
loss is :  1.3269835
loss is :  1.327364
loss is :  1.327561
loss is :  1.3279415
loss is :  1.3281431
loss is :  1.3285187
loss is :  1.3287061
loss is :  1.3290724
loss is :  1.329226
loss is :  1.3295786
loss is :  1.3296797
loss is :  1.3300159
loss 

loss is :  1.3259501
loss is :  1.325737
loss is :  1.3260567
loss is :  1.3258218
loss is :  1.3261346
loss is :  1.3258792
loss is :  1.326182
loss is :  1.3259081
loss is :  1.3261977
loss is :  1.3259077
loss is :  1.3261819
loss is :  1.3258791
loss is :  1.3261358
loss is :  1.3258232
loss is :  1.3260616
loss is :  1.3257427
loss is :  1.3259623
loss is :  1.3256403
loss is :  1.3258412
loss is :  1.3255196
loss is :  1.3257024
loss is :  1.325384
loss is :  1.3255498
loss is :  1.3252368
loss is :  1.325387
loss is :  1.3250818
loss is :  1.3252177
loss is :  1.3249218
loss is :  1.3250451
loss is :  1.32476
loss is :  1.3248725
loss is :  1.3245987
loss is :  1.3247018
loss is :  1.3244401
loss is :  1.3245354
loss is :  1.3242859
loss is :  1.3243749
loss is :  1.3241374
loss is :  1.3242216
loss is :  1.323996
loss is :  1.3240767
loss is :  1.3238622
loss is :  1.3239405
loss is :  1.323737
loss is :  1.3238139
loss is :  1.3236207
loss is :  1.3236971
loss is :  1.323513
l

loss is :  1.3258052
loss is :  1.3255173
loss is :  1.3255847
loss is :  1.3253076
loss is :  1.3253739
loss is :  1.3251075
loss is :  1.3251739
loss is :  1.3249176
loss is :  1.3249843
loss is :  1.3247378
loss is :  1.3248055
loss is :  1.3245683
loss is :  1.3246378
loss is :  1.324409
loss is :  1.3244807
loss is :  1.32426
loss is :  1.3243339
loss is :  1.324121
loss is :  1.3241975
loss is :  1.3239918
loss is :  1.3240709
loss is :  1.323872
loss is :  1.3239541
loss is :  1.3237615
loss is :  1.3238466
loss is :  1.3236595
loss is :  1.3237479
loss is :  1.323566
loss is :  1.3236574
loss is :  1.3234806
loss is :  1.3235753
loss is :  1.3234029
loss is :  1.3235006
loss is :  1.3233325
loss is :  1.3234332
loss is :  1.323269
loss is :  1.3233726
loss is :  1.323212
loss is :  1.3233185
loss is :  1.3231611
loss is :  1.3232703
loss is :  1.3231158
loss is :  1.3232279
loss is :  1.3230764
loss is :  1.3231909
loss is :  1.3230417
loss is :  1.3231589
loss is :  1.3230119


loss is :  1.3231571
loss is :  1.3230234
loss is :  1.3230629
loss is :  1.3229364
loss is :  1.3229755
loss is :  1.3228554
loss is :  1.3228947
loss is :  1.3227805
loss is :  1.3228205
loss is :  1.3227118
loss is :  1.3227526
loss is :  1.3226492
loss is :  1.3226911
loss is :  1.3225921
loss is :  1.3226359
loss is :  1.3225411
loss is :  1.3225867
loss is :  1.3224955
loss is :  1.3225433
loss is :  1.3224555
loss is :  1.3225058
loss is :  1.322421
loss is :  1.3224741
loss is :  1.3223916
loss is :  1.3224478
loss is :  1.3223677
loss is :  1.322427
loss is :  1.3223488
loss is :  1.3224119
loss is :  1.3223352
loss is :  1.3224022
loss is :  1.3223265
loss is :  1.3223978
loss is :  1.3223232
loss is :  1.3223993
loss is :  1.3223249
loss is :  1.3224058
loss is :  1.3223318
loss is :  1.3224181
loss is :  1.3223441
loss is :  1.3224359
loss is :  1.3223614
loss is :  1.3224595
loss is :  1.322384
loss is :  1.3224887
loss is :  1.3224121
loss is :  1.3225238
loss is :  1.322

loss is :  1.3223069
loss is :  1.3223095
loss is :  1.3223257
loss is :  1.3223349
loss is :  1.3223529
loss is :  1.3223699
loss is :  1.322389
loss is :  1.3224163
loss is :  1.3224363
loss is :  1.322476
loss is :  1.3224964
loss is :  1.3225516
loss is :  1.3225718
loss is :  1.3226457
loss is :  1.3226646
loss is :  1.3227614
loss is :  1.3227781
loss is :  1.3229023
loss is :  1.3229156
loss is :  1.3230721
loss is :  1.3230803
loss is :  1.3232745
loss is :  1.3232756
loss is :  1.3235133
loss is :  1.3235047
loss is :  1.3237915
loss is :  1.3237697
loss is :  1.3241099
loss is :  1.3240714
loss is :  1.3244687
loss is :  1.3244085
loss is :  1.3248639
loss is :  1.3247768
loss is :  1.3252885
loss is :  1.3251681
loss is :  1.3257307
loss is :  1.3255706
loss is :  1.3261747
loss is :  1.325969
loss is :  1.3266017
loss is :  1.3263446
loss is :  1.3269907
loss is :  1.3266786
loss is :  1.3273219
loss is :  1.3269535
loss is :  1.327579
loss is :  1.327156
loss is :  1.32775

loss is :  1.3231165
loss is :  1.3232572
loss is :  1.3230689
loss is :  1.3232054
loss is :  1.3230219
loss is :  1.3231542
loss is :  1.3229756
loss is :  1.3231038
loss is :  1.3229301
loss is :  1.3230543
loss is :  1.3228856
loss is :  1.3230059
loss is :  1.3228421
loss is :  1.322959
loss is :  1.3227997
loss is :  1.3229129
loss is :  1.3227586
loss is :  1.3228681
loss is :  1.3227184
loss is :  1.3228248
loss is :  1.3226799
loss is :  1.3227831
loss is :  1.3226423
loss is :  1.3227427
loss is :  1.3226062
loss is :  1.3227037
loss is :  1.3225715
loss is :  1.3226663
loss is :  1.3225379
loss is :  1.3226305
loss is :  1.322506
loss is :  1.3225958
loss is :  1.3224751
loss is :  1.3225628
loss is :  1.3224459
loss is :  1.3225313
loss is :  1.3224176
loss is :  1.3225012
loss is :  1.3223907
loss is :  1.3224726
loss is :  1.3223653
loss is :  1.3224454
loss is :  1.3223411
loss is :  1.3224195
loss is :  1.322318
loss is :  1.322395
loss is :  1.3222963
loss is :  1.3223

loss is :  1.3232553
loss is :  1.3234168
loss is :  1.3233558
loss is :  1.3235176
loss is :  1.3234537
loss is :  1.3236138
loss is :  1.3235475
loss is :  1.3237044
loss is :  1.3236357
loss is :  1.3237882
loss is :  1.3237177
loss is :  1.323864
loss is :  1.3237921
loss is :  1.3239305
loss is :  1.3238579
loss is :  1.3239874
loss is :  1.3239146
loss is :  1.3240336
loss is :  1.3239617
loss is :  1.3240689
loss is :  1.3239983
loss is :  1.324093
loss is :  1.3240248
loss is :  1.3241059
loss is :  1.3240405
loss is :  1.3241079
loss is :  1.3240464
loss is :  1.3240995
loss is :  1.3240426
loss is :  1.3240813
loss is :  1.3240296
loss is :  1.3240541
loss is :  1.3240081
loss is :  1.324019
loss is :  1.323979
loss is :  1.3239763
loss is :  1.323943
loss is :  1.3239276
loss is :  1.3239012
loss is :  1.3238739
loss is :  1.3238544
loss is :  1.323816
loss is :  1.3238035
loss is :  1.3237549
loss is :  1.3237495
loss is :  1.3236915
loss is :  1.3236933
loss is :  1.323627

loss is :  1.3212037
loss is :  1.3211915
loss is :  1.3211889
loss is :  1.3211776
loss is :  1.3211755
loss is :  1.3211654
loss is :  1.3211637
loss is :  1.3211546
loss is :  1.3211533
loss is :  1.3211452
loss is :  1.3211445
loss is :  1.3211373
loss is :  1.3211368
loss is :  1.3211306
loss is :  1.3211306
loss is :  1.3211255
loss is :  1.3211259
loss is :  1.3211216
loss is :  1.3211226
loss is :  1.3211193
loss is :  1.3211207
loss is :  1.3211184
loss is :  1.3211205
loss is :  1.3211191
loss is :  1.3211218
loss is :  1.3211216
loss is :  1.3211248
loss is :  1.3211259
loss is :  1.3211298
loss is :  1.3211322
loss is :  1.3211368
loss is :  1.3211405
loss is :  1.3211461
loss is :  1.3211515
loss is :  1.321158
loss is :  1.3211652
loss is :  1.3211727
loss is :  1.3211819
loss is :  1.3211907
loss is :  1.321202
loss is :  1.3212122
loss is :  1.3212262
loss is :  1.3212379
loss is :  1.3212551
loss is :  1.3212683
loss is :  1.3212888
loss is :  1.3213041
loss is :  1.32

loss is :  1.3233042
loss is :  1.323492
loss is :  1.3233805
loss is :  1.3235757
loss is :  1.323455
loss is :  1.323657
loss is :  1.3235271
loss is :  1.3237352
loss is :  1.3235959
loss is :  1.3238091
loss is :  1.3236604
loss is :  1.3238779
loss is :  1.32372
loss is :  1.3239409
loss is :  1.3237741
loss is :  1.3239968
loss is :  1.3238217
loss is :  1.3240451
loss is :  1.3238622
loss is :  1.3240849
loss is :  1.3238952
loss is :  1.3241158
loss is :  1.3239202
loss is :  1.3241372
loss is :  1.3239368
loss is :  1.3241491
loss is :  1.3239449
loss is :  1.324151
loss is :  1.3239444
loss is :  1.3241434
loss is :  1.3239355
loss is :  1.324126
loss is :  1.3239183
loss is :  1.3240995
loss is :  1.323893
loss is :  1.3240641
loss is :  1.3238602
loss is :  1.3240206
loss is :  1.3238201
loss is :  1.3239696
loss is :  1.3237735
loss is :  1.3239119
loss is :  1.3237214
loss is :  1.3238482
loss is :  1.3236642
loss is :  1.3237797
loss is :  1.3236023
loss is :  1.323707
l

loss is :  1.3240392
loss is :  1.3239391
loss is :  1.323947
loss is :  1.3238391
loss is :  1.3238604
loss is :  1.3237456
loss is :  1.323781
loss is :  1.32366
loss is :  1.3237085
loss is :  1.3235819
loss is :  1.3236437
loss is :  1.323512
loss is :  1.3235862
loss is :  1.3234499
loss is :  1.3235351
loss is :  1.3233949
loss is :  1.3234907
loss is :  1.323347
loss is :  1.3234518
loss is :  1.3233052
loss is :  1.323418
loss is :  1.3232689
loss is :  1.3233885
loss is :  1.3232373
loss is :  1.3233622
loss is :  1.3232094
loss is :  1.3233386
loss is :  1.3231847
loss is :  1.323317
loss is :  1.3231622
loss is :  1.3232965
loss is :  1.323141
loss is :  1.3232764
loss is :  1.3231207
loss is :  1.323256
loss is :  1.3231001
loss is :  1.323235
loss is :  1.3230795
loss is :  1.3232129
loss is :  1.3230579
loss is :  1.323189
loss is :  1.323035
loss is :  1.3231635
loss is :  1.3230104
loss is :  1.3231362
loss is :  1.3229841
loss is :  1.3231069
loss is :  1.3229562
loss 

loss is :  1.3222531
loss is :  1.3223234
loss is :  1.3222826
loss is :  1.3223535
loss is :  1.3223128
loss is :  1.3223845
loss is :  1.3223442
loss is :  1.3224161
loss is :  1.3223759
loss is :  1.3224481
loss is :  1.3224081
loss is :  1.3224803
loss is :  1.3224404
loss is :  1.3225129
loss is :  1.3224727
loss is :  1.322545
loss is :  1.3225049
loss is :  1.322577
loss is :  1.3225366
loss is :  1.3226081
loss is :  1.3225676
loss is :  1.3226385
loss is :  1.3225974
loss is :  1.3226676
loss is :  1.3226264
loss is :  1.3226955
loss is :  1.3226538
loss is :  1.322722
loss is :  1.3226796
loss is :  1.3227465
loss is :  1.3227036
loss is :  1.3227689
loss is :  1.3227258
loss is :  1.3227893
loss is :  1.3227456
loss is :  1.3228077
loss is :  1.3227632
loss is :  1.3228235
loss is :  1.3227783
loss is :  1.3228366
loss is :  1.322791
loss is :  1.3228471
loss is :  1.322801
loss is :  1.3228549
loss is :  1.3228083
loss is :  1.3228598
loss is :  1.3228127
loss is :  1.32286

loss is :  1.3222578
loss is :  1.3222443
loss is :  1.3222487
loss is :  1.322234
loss is :  1.3222413
loss is :  1.3222251
loss is :  1.3222355
loss is :  1.3222178
loss is :  1.322231
loss is :  1.3222121
loss is :  1.3222286
loss is :  1.3222086
loss is :  1.3222281
loss is :  1.3222071
loss is :  1.3222296
loss is :  1.3222076
loss is :  1.3222337
loss is :  1.3222109
loss is :  1.3222401
loss is :  1.3222166
loss is :  1.3222493
loss is :  1.322225
loss is :  1.3222613
loss is :  1.3222364
loss is :  1.3222762
loss is :  1.3222511
loss is :  1.3222948
loss is :  1.322269
loss is :  1.3223164
loss is :  1.3222905
loss is :  1.3223422
loss is :  1.3223158
loss is :  1.3223715
loss is :  1.3223448
loss is :  1.3224047
loss is :  1.3223782
loss is :  1.3224425
loss is :  1.3224157
loss is :  1.3224845
loss is :  1.322458
loss is :  1.3225312
loss is :  1.3225048
loss is :  1.3225825
loss is :  1.322556
loss is :  1.3226385
loss is :  1.322612
loss is :  1.3226994
loss is :  1.3226731

loss is :  1.3250512
loss is :  1.3249142
loss is :  1.3254393
loss is :  1.3252789
loss is :  1.3258234
loss is :  1.3256358
loss is :  1.3261887
loss is :  1.3259714
loss is :  1.3265196
loss is :  1.3262715
loss is :  1.3268021
loss is :  1.3265245
loss is :  1.327025
loss is :  1.326721
loss is :  1.3271805
loss is :  1.3268548
loss is :  1.3272651
loss is :  1.3269243
loss is :  1.3272799
loss is :  1.3269309
loss is :  1.3272288
loss is :  1.3268785
loss is :  1.3271189
loss is :  1.3267739
loss is :  1.3269591
loss is :  1.3266252
loss is :  1.3267586
loss is :  1.3264403
loss is :  1.3265274
loss is :  1.326228
loss is :  1.3262739
loss is :  1.3259957
loss is :  1.3260065
loss is :  1.3257506
loss is :  1.3257322
loss is :  1.3254988
loss is :  1.3254563
loss is :  1.3252453
loss is :  1.325184
loss is :  1.3249941
loss is :  1.3249183
loss is :  1.3247485
loss is :  1.3246622
loss is :  1.3245109
loss is :  1.3244176
loss is :  1.3242832
loss is :  1.3241854
loss is :  1.3240

loss is :  1.3234149
loss is :  1.3233702
loss is :  1.323413
loss is :  1.323367
loss is :  1.3234067
loss is :  1.3233598
loss is :  1.3233962
loss is :  1.3233489
loss is :  1.3233815
loss is :  1.3233341
loss is :  1.3233633
loss is :  1.3233159
loss is :  1.323341
loss is :  1.3232945
loss is :  1.3233156
loss is :  1.3232698
loss is :  1.3232867
loss is :  1.3232422
loss is :  1.3232548
loss is :  1.3232123
loss is :  1.3232204
loss is :  1.3231798
loss is :  1.3231837
loss is :  1.3231453
loss is :  1.3231449
loss is :  1.3231094
loss is :  1.3231045
loss is :  1.3230716
loss is :  1.3230627
loss is :  1.3230332
loss is :  1.32302
loss is :  1.3229938
loss is :  1.3229764
loss is :  1.3229537
loss is :  1.3229326
loss is :  1.3229139
loss is :  1.3228887
loss is :  1.3228741
loss is :  1.3228456
loss is :  1.3228347
loss is :  1.3228025
loss is :  1.3227963
loss is :  1.3227608
loss is :  1.3227589
loss is :  1.3227203
loss is :  1.322723
loss is :  1.3226812
loss is :  1.322688

loss is :  1.3219839
loss is :  1.3219488
loss is :  1.3219804
loss is :  1.3219463
loss is :  1.3219782
loss is :  1.3219452
loss is :  1.3219777
loss is :  1.321946
loss is :  1.321979
loss is :  1.3219484
loss is :  1.3219824
loss is :  1.3219528
loss is :  1.3219879
loss is :  1.3219595
loss is :  1.3219955
loss is :  1.3219688
loss is :  1.3220059
loss is :  1.3219807
loss is :  1.3220192
loss is :  1.3219956
loss is :  1.3220356
loss is :  1.3220136
loss is :  1.3220555
loss is :  1.3220354
loss is :  1.3220791
loss is :  1.3220611
loss is :  1.3221068
loss is :  1.3220911
loss is :  1.3221389
loss is :  1.3221258
loss is :  1.3221759
loss is :  1.3221655
loss is :  1.3222183
loss is :  1.3222108
loss is :  1.3222661
loss is :  1.3222619
loss is :  1.32232
loss is :  1.3223195
loss is :  1.3223802
loss is :  1.3223835
loss is :  1.322447
loss is :  1.3224547
loss is :  1.3225209
loss is :  1.322533
loss is :  1.322602
loss is :  1.3226188
loss is :  1.3226902
loss is :  1.3227122

loss is :  1.3218288
loss is :  1.3218348
loss is :  1.3218131
loss is :  1.3218194
loss is :  1.3217974
loss is :  1.3218043
loss is :  1.3217818
loss is :  1.3217888
loss is :  1.3217659
loss is :  1.3217735
loss is :  1.3217502
loss is :  1.3217585
loss is :  1.3217347
loss is :  1.3217437
loss is :  1.3217195
loss is :  1.3217291
loss is :  1.3217046
loss is :  1.3217149
loss is :  1.32169
loss is :  1.3217012
loss is :  1.3216759
loss is :  1.321688
loss is :  1.3216622
loss is :  1.3216753
loss is :  1.321649
loss is :  1.3216631
loss is :  1.3216364
loss is :  1.3216518
loss is :  1.3216248
loss is :  1.3216412
loss is :  1.3216137
loss is :  1.3216316
loss is :  1.3216035
loss is :  1.3216228
loss is :  1.3215945
loss is :  1.3216153
loss is :  1.3215866
loss is :  1.3216091
loss is :  1.3215799
loss is :  1.3216041
loss is :  1.3215743
loss is :  1.3216008
loss is :  1.3215705
loss is :  1.321599
loss is :  1.3215684
loss is :  1.3215992
loss is :  1.321568
loss is :  1.321601

loss is :  1.3242631
loss is :  1.3242625
loss is :  1.3242311
loss is :  1.3242326
loss is :  1.324193
loss is :  1.3241963
loss is :  1.3241491
loss is :  1.3241549
loss is :  1.3241007
loss is :  1.3241085
loss is :  1.324048
loss is :  1.324058
loss is :  1.3239924
loss is :  1.3240042
loss is :  1.3239343
loss is :  1.3239478
loss is :  1.3238747
loss is :  1.3238894
loss is :  1.3238145
loss is :  1.3238299
loss is :  1.3237544
loss is :  1.32377
loss is :  1.3236952
loss is :  1.3237106
loss is :  1.3236378
loss is :  1.3236523
loss is :  1.3235824
loss is :  1.3235956
loss is :  1.3235297
loss is :  1.323541
loss is :  1.3234805
loss is :  1.3234893
loss is :  1.3234346
loss is :  1.3234408
loss is :  1.3233929
loss is :  1.3233956
loss is :  1.3233553
loss is :  1.3233541
loss is :  1.3233222
loss is :  1.3233168
loss is :  1.3232938
loss is :  1.3232837
loss is :  1.3232698
loss is :  1.3232546
loss is :  1.3232505
loss is :  1.3232299
loss is :  1.3232355
loss is :  1.323209

loss is :  1.3219273
loss is :  1.3218985
loss is :  1.321917
loss is :  1.3218896
loss is :  1.3219075
loss is :  1.3218815
loss is :  1.3218988
loss is :  1.3218741
loss is :  1.3218908
loss is :  1.3218675
loss is :  1.3218834
loss is :  1.3218614
loss is :  1.321877
loss is :  1.3218559
loss is :  1.3218712
loss is :  1.3218511
loss is :  1.3218659
loss is :  1.321847
loss is :  1.3218613
loss is :  1.3218431
loss is :  1.3218575
loss is :  1.3218402
loss is :  1.3218541
loss is :  1.3218377
loss is :  1.3218513
loss is :  1.3218355
loss is :  1.3218492
loss is :  1.3218341
loss is :  1.3218477
loss is :  1.3218333
loss is :  1.3218467
loss is :  1.3218328
loss is :  1.3218461
loss is :  1.3218327
loss is :  1.3218462
loss is :  1.3218331
loss is :  1.3218467
loss is :  1.3218341
loss is :  1.3218478
loss is :  1.3218355
loss is :  1.3218492
loss is :  1.3218374
loss is :  1.3218513
loss is :  1.3218395
loss is :  1.3218538
loss is :  1.3218423
loss is :  1.3218566
loss is :  1.321

loss is :  1.3225758
loss is :  1.3226646
loss is :  1.3225309
loss is :  1.3226154
loss is :  1.3224858
loss is :  1.3225659
loss is :  1.3224407
loss is :  1.3225172
loss is :  1.3223963
loss is :  1.3224689
loss is :  1.3223525
loss is :  1.3224216
loss is :  1.3223096
loss is :  1.3223754
loss is :  1.3222678
loss is :  1.3223304
loss is :  1.322227
loss is :  1.3222867
loss is :  1.3221875
loss is :  1.3222445
loss is :  1.3221498
loss is :  1.3222039
loss is :  1.3221134
loss is :  1.3221651
loss is :  1.3220783
loss is :  1.3221278
loss is :  1.3220452
loss is :  1.3220927
loss is :  1.3220137
loss is :  1.3220592
loss is :  1.3219842
loss is :  1.3220277
loss is :  1.3219562
loss is :  1.321998
loss is :  1.3219299
loss is :  1.3219705
loss is :  1.3219057
loss is :  1.3219446
loss is :  1.3218833
loss is :  1.3219209
loss is :  1.3218623
loss is :  1.3218989
loss is :  1.3218436
loss is :  1.3218789
loss is :  1.3218268
loss is :  1.3218609
loss is :  1.3218116
loss is :  1.32

loss is :  1.3217299
loss is :  1.3217207
loss is :  1.3217326
loss is :  1.3217232
loss is :  1.3217356
loss is :  1.3217261
loss is :  1.3217381
loss is :  1.3217288
loss is :  1.3217407
loss is :  1.3217313
loss is :  1.3217432
loss is :  1.3217341
loss is :  1.3217453
loss is :  1.3217363
loss is :  1.3217474
loss is :  1.3217382
loss is :  1.3217492
loss is :  1.3217402
loss is :  1.3217506
loss is :  1.3217419
loss is :  1.3217518
loss is :  1.3217434
loss is :  1.3217528
loss is :  1.3217443
loss is :  1.3217533
loss is :  1.3217449
loss is :  1.3217534
loss is :  1.3217454
loss is :  1.3217531
loss is :  1.3217454
loss is :  1.3217525
loss is :  1.321745
loss is :  1.3217515
loss is :  1.3217442
loss is :  1.3217502
loss is :  1.3217431
loss is :  1.3217481
loss is :  1.3217417
loss is :  1.321746
loss is :  1.3217397
loss is :  1.3217434
loss is :  1.3217375
loss is :  1.3217403
loss is :  1.3217349
loss is :  1.3217368
loss is :  1.3217318
loss is :  1.3217329
loss is :  1.32

In [21]:
print(sess.run(W1))
print('----------')
print(sess.run(b1))
print('----------')

[[-0.54291445  1.0212634  -0.5825733  -0.37094423 -2.4117281  -0.85852915
  -0.74192625]
 [-0.47693086  0.43349394  1.183156    1.2009467  -1.4332757   0.6423036
  -0.5689882 ]
 [-0.5209593  -1.0147674  -0.03722442 -1.361735    1.3838059   2.775302
   1.9411644 ]
 [-0.6070819   0.5716274   1.9830558   0.5855507   1.2730329  -1.0580144
  -1.17597   ]
 [-0.88925433  0.4959117   1.4636309   0.8804558   1.7076277  -1.1376796
  -1.2775079 ]
 [ 0.68160766  0.8828667  -2.2205908  -1.6298815  -0.11409569 -1.4273703
   0.90677077]
 [ 2.834611   -2.1975412   0.7366071   0.91583747 -0.5145942   0.48424688
  -1.1476259 ]]
----------
[-0.63575053  0.18814427 -0.05379883  1.0369028  -0.38867626 -0.4223758
 -0.0771817 ]
----------


In [22]:
vectors = sess.run(W1 + b1)

In [23]:
print(vectors)

[[-1.1786649   1.2094076  -0.63637215  0.6659585  -2.8004043  -1.280905
  -0.81910795]
 [-1.1126814   0.6216382   1.1293572   2.2378495  -1.821952    0.21992779
  -0.6461699 ]
 [-1.1567099  -0.82662314 -0.09102324 -0.3248322   0.9951296   2.3529263
   1.8639827 ]
 [-1.2428324   0.75977165  1.929257    1.6224535   0.8843566  -1.4803902
  -1.2531517 ]
 [-1.5250049   0.6840559   1.4098321   1.9173586   1.3189514  -1.5600554
  -1.3546896 ]
 [ 0.04585713  1.071011   -2.2743897  -0.5929787  -0.502772   -1.8497461
   0.82958907]
 [ 2.1988604  -2.009397    0.6828082   1.9527402  -0.9032705   0.06187108
  -1.2248076 ]]


In [24]:
def euclidean_dist(vec1, vec2):
    return np.sqrt(np.sum((vec1-vec2)**2))

def find_closest(word_index, vectors):
    min_dist = 9999
    min_index = -1
    
    query_vector = vectors[word_index]
    
    for index, vector in enumerate(vectors):
        if euclidean_dist(vector, query_vector) < min_dist and not np.array_equal(vector, query_vector):
            min_dist = euclidean_dist(vector, query_vector)
            min_index = index
    return min_index

In [25]:
print(i2w[find_closest(w2i['king'], vectors)])

queen


In [26]:
print(i2w[find_closest(w2i['queen'], vectors)])

king


In [27]:
print(i2w[find_closest(w2i['royal'], vectors)])

king
